[package]
name          = "azure_sdk_for_rust"
version       = "0.10.2"
description   = "Rust wrappers around Microsoft Azure REST APIs"
readme        = "README.md"
authors       = ["Francesco Cogno <francesco.cogno@outlook.com>", "Max Gortman <mgortman@microsoft.com>", "Dong Liu <doliu@microsoft.com>"]
license       = "Apache-2.0"
repository    = "https://github.com/MindFlavor/AzureSDKForRust"
documentation = "http://mindflavor.github.io/AzureSDKForRust/azure_sdk_for_rust/index.html"
homepage      = "https://github.com/MindFlavor/AzureSDKForRust"

keywords      = ["sdk", "azure", "rest", "iot", "cloud"]
categories    = ["api-bindings"]

edition       = "2018"

[dependencies]
ring         = "0.13"
md5          = "0.4"
RustyXML     = "0.1"
base64       = "0.9"
chrono       = "0.4"
env_logger   = "0.5"
futures      = "0.1"
hmac-sha256 = "0.1.1"
http         = "0.1"
hyper        = "0.12"
hyper-tls    = "0.3"
log          = "0.4"
mime         = "0.3"
quick-error  = "1.2"
serde        = "=1.0.82"
serde_derive = "1.0"
serde_json   = "1.0"
serde-xml-rs = "0.2"
time         = "0.1"
url          = "1.7"
uuid         = { version = "0.7", features = ["v4"] }
smallvec     = { version = "0.6", features = ["serde"] }
bytes        = "0.4"

[dev-dependencies]
tokio-core   = "0.1"

[features]
test_e2e       = []
